spring:
  application:
    name: eureka-server-instance-2
  boot:
    admin:
      context-path: /admin
server:
  port: 8072
eureka:
  instance:
    hostname: eureka-instance-2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka, http://eureka-instance-3:8070/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 5


management:
  endpoints:
    web:
      exposure:
        include: "*"

